version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A proposta_projeto worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    links:
      - db
    restart: on-failure

volumes:
  postgres_data:
