# Generated by Django 4.2.2 on 2023-06-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalResponseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.CharField(max_length=100)),
                ('proposal_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.proposalfield')),
                ('response_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propostas.proposalresponse')),
            ],
        ),
        migrations.AddField(
            model_name='proposalresponse',
            name='fields',
            field=models.ManyToManyField(through='propostas.ProposalResponseField', to='propostas.proposalfield'),
        ),
        migrations.AddField(
            model_name='proposalresponse',
            name='proposal_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='propostas.proposal'),
        ),
    ]
